# authentication error messages
authentication.err.validation.authenticator.notfound=Kan verificatie niet uitvoeren, verificator met naam, {0}, niet gevonden
authentication.err.validation.authenticator.notactive=De verificator is niet actief

authentication.err.authentication=Kan verificatie niet uitvoeren, gebruikersnaam of wachtwoord is onjuist. Gebruikersnaam:{0} Reden {1}
authentication.err.connection=Kan geen verbinding maken met {0}. Reden {1}
authentication.err.communication=Kan niet communiceren met {0}. Reden {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Kan geen verbinding maken, de LDAP-host {0} is onbekend
authentication.err.connection.ldap.user.notfound=LDAP-gebruiker {0} niet gevonden
authentication.err.connection.ldap.manager.notfound=LDAP-beheerdergebruiker {0} niet gevonden
authentication.err.connection.ldap.search=Kan niet zoeken naar LDAP. Reden {0}

# PASSTHRU
authentication.err.connection.passthru.server=Kan sessie met Passthru-server niet openen
authentication.err.passthru.token.unsupported=Niet-ondersteund type verificatietoken
authentication.err.passthru.guest.notenabled=Gastaanmeldingen uitgeschakeld
authentication.err.passthru.user.disabled=Account uitgeschakeld
authentication.err.passthru.user.notfound=Passthru-gebruiker {0} niet gevonden

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validatie van aanvraag
authentication.step.ldap.connecting=Verbinding maken LDAP-server {0} 
authentication.step.ldap.connected=Verbonden met LDAP-server {0} met principal: {1}
authentication.step.ldap.lookup=Zoeken naar gebruikers-id van testgebruiker:{0} met query: {1}
authentication.step.ldap.lookedup=Gezocht naar gebruikers-id van testgebruiker:{0}, Distinguished Name (DN) gevonden:{1}
authentication.step.ldap.format.user=Notatie voor gebruikersnaam opgegeven, gebruikersnaamnotatie:{2} Notatie gebruiker gebruikers-id:{0} voor maken van Distinguished Name (DN):{1}
authentication.step.ldap.authentication=Gebruikers-id verifi\u00ebren:{0}


# Sync Summary message 
synchronization.summary.status={0} gebruiker(s) en {1} groep(en) verwerkt


# Error messages
authentication.ldap.validation.authenticator.notfound=Verificator niet gevonden

# Synchronization Diagnostic Steps
synchronization.step.users={0} gebruikers gevonden
synchronization.step.groups={0} groepen gevonden
synchronization.step.users.lastsynced=Gebruikers die het laatst gesynchroniseerd zijn {0}
synchronization.step.groups.lastsynced=Groepen die het laatst gesynchroniseerd zijn {0}

synchronization.err.ldap.search=Fout tijdens LDAP-zoeken Reden:{0}
synchronization.err.ldap.get.user.id.missing=Gebruiker mist gebruikers-id attribuut DN = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Groep mist groeps-id attribuut DN = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Ongeldige zoekargument {0} reden: {1}

synchronization.err.ldap.group.member.missing.exception="Het oplossen van lid van groep {0} met onderscheidende naam is mislukt: {1}, reden {2});
synchronization.err.ldap.group.member.missing="Het oplossen van lid van groep {0} met onderscheidende naam is mislukt: {1});



       



