# authentication error messages
authentication.err.validation.authenticator.notfound=Failed to authenticate, authenticator with name, {0}, not found
authentication.err.validation.authenticator.notactive=The authenticator is not active

authentication.err.authentication=Failed to authenticate, username or password is wrong. User name:{0} Reason {1}
authentication.err.connection=Failed to connect to {0}. Reason {1}
authentication.err.communication=Failed to communicate with {0}. Reason {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Failed to connect, the ldap host {0} is unknown
authentication.err.connection.ldap.user.notfound=LDAP User {0} not found
authentication.err.connection.ldap.manager.notfound=LDAP Manager User {0} not found
authentication.err.connection.ldap.search=Unable to search LDAP. Reason {0}

# PASSTHRU
authentication.err.connection.passthru.server=Failed to open session to passthru server
authentication.err.passthru.token.unsupported=Unsupported authentication token type
authentication.err.passthru.guest.notenabled=Guest logons disabled
authentication.err.passthru.user.disabled=Account disabled
authentication.err.passthru.user.notfound=Passthru user {0} not found

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validation of request
authentication.step.ldap.connecting=Connecting to LDAP Server {0} 
authentication.step.ldap.connected=Connected to LDAP server {0} with principal: {1}
authentication.step.ldap.lookup=Lookup Test User userId:{0} with query: {1}
authentication.step.ldap.lookedup=Looked up Test User userId:{0}, found distinguished name (DN):{1}
authentication.step.ldap.format.user=User Name Format specified, userNameFormat:{2} Format user userId:{0} to make Distinguished name (DN):{1}
authentication.step.ldap.authentication=Authenticate userId:{0}


# Sync Summary message 
synchronization.summary.status={0} user(s) and {1} group(s) processed


# Error messages
authentication.ldap.validation.authenticator.notfound=Authenticator not found

# Synchronization Diagnostic Steps
synchronization.step.users=Found {0} users
synchronization.step.groups=Found {0} groups
synchronization.step.users.lastsynced=Users last successfully synced {0}
synchronization.step.groups.lastsynced=Groups last successfully synced {0}

synchronization.err.ldap.search=Error during LDAP Search. Reason:{0}
synchronization.err.ldap.get.user.id.missing=User missing user id attribute DN = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Group missing group id attribute DN = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Invalid search base {0} reason: {1}

synchronization.err.ldap.group.member.missing.exception="Failed to resolve member of group {0} with distinguished name: {1}, reason {2});
synchronization.err.ldap.group.member.missing="Failed to resolve member of group {0} with distinguished name: {1});



       



