# authentication error messages
authentication.err.validation.authenticator.notfound=Fallo de autenticaci\u00f3n, no se encontr\u00f3 el autenticador {0}
authentication.err.validation.authenticator.notactive=El autenticador no est\u00e1 activo

authentication.err.authentication=Fallo de autenticaci\u00f3n, nombre de usuario o contrase\u00f1a incorrectos. Nombre de usuario:{0} Raz\u00f3n {1}
authentication.err.connection=Fallo de conexi\u00f3n a {0}. Raz\u00f3n {1}
authentication.err.communication=Fallo de comunicaci\u00f3n con {0}. Raz\u00f3n {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Fallo de conexi\u00f3n, host LDAP {0} desconocido
authentication.err.connection.ldap.user.notfound=No se encontr\u00f3 el usuario LDAP {0}
authentication.err.connection.ldap.manager.notfound=No se encontr\u00f3 el usuario administrador LDAP {0}
authentication.err.connection.ldap.search=No se pudo buscar LDAP. Raz\u00f3n {0}

# PASSTHRU
authentication.err.connection.passthru.server=No se pudo abrir una sesi\u00f3n en el servidor passthru
authentication.err.passthru.token.unsupported=Tipo de token de autenticaci\u00f3n no compatible
authentication.err.passthru.guest.notenabled=Inicios de sesi\u00f3n como invitado deshabilitados
authentication.err.passthru.user.disabled=Cuenta deshabilitada
authentication.err.passthru.user.notfound=No se encontr\u00f3 el usuario passthru {0}

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validaci\u00f3n de solicitud
authentication.step.ldap.connecting=Conectando al servidor LDAP {0} 
authentication.step.ldap.connected=Conectado al servidor LDAP {0} con principal: {1}
authentication.step.ldap.lookup=Buscar Id. de usuario de prueba:{0} con consulta: {1}
authentication.step.ldap.lookedup=Id. de usuario de prueba buscado:{0}, se encontr\u00f3 nombre distintivo (DN):{1}
authentication.step.ldap.format.user=Formato de nombre de usuario especificado, formato de nombre de usuario:{2} formatear Id. de usuario de usuario:{0} para crear nombre distintivo (DN):{1}
authentication.step.ldap.authentication=Id. de usuario aut\u00e9ntico:{0}


# Sync Summary message 
synchronization.summary.status={0} usuarios y {1} grupos procesados


# Error messages
authentication.ldap.validation.authenticator.notfound=Autenticador no encontrado

# Synchronization Diagnostic Steps
synchronization.step.users=Se han encontrado {0} usuarios
synchronization.step.groups=Se han encontrado {0} grupos
synchronization.step.users.lastsynced=Usuarios en la \u00faltima sincronizaci\u00f3n correcta {0}
synchronization.step.groups.lastsynced=Grupos en la \u00faltima sincronizaci\u00f3n correcta {0}

synchronization.err.ldap.search=Error durante la b\u00fasqueda LDAP. Raz\u00f3n: {0}
synchronization.err.ldap.get.user.id.missing=Al usuario le falta el DN del atributo de Id. de usuario = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Al grupo le falta el DN del atributo de Id. de grupo = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Base de b\u00fasqueda no v\u00e1lida {0}. Raz\u00f3n: {1}

synchronization.err.ldap.group.member.missing.exception=No se pudo resolver el miembro del grupo {0} con el nombre distintivo: {1}, raz\u00f3n {2});
synchronization.err.ldap.group.member.missing=No se pudo resolver el miembro del grupo {0} con el nombre distintivo: {1});



       



